# -*- coding: utf-8 -*-
"""dashboard_simulasi_siswaa

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QozICh8ezqeCgUdPWVf-Yrcu3tvRb89u
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

# ==========================================================
# KONFIGURASI HALAMAN
# ==========================================================
st.set_page_config(page_title="Dashboard Analisis Siswa", layout="wide")
st.title("📊 Dashboard Analisis Hasil Simulasi Siswa")
st.write("Analisis otomatis untuk data 50 siswa dan 20 soal")

# ==========================================================
# INPUT DATA
# ==========================================================
uploaded_file = st.file_uploader("Upload file Excel", type=["xlsx"])

if uploaded_file is None:
    st.warning("Silakan upload file Excel terlebih dahulu.")
    st.stop()

# ==========================================================
# MEMBACA DATA
# ==========================================================
try:
    df = pd.read_excel(uploaded_file)
    indikator = df.apply(pd.to_numeric, errors="coerce")
except Exception as e:
    st.error(f"Gagal membaca file: {e}")
    st.stop()

# ==========================================================
# KPI KEPUASAN / CAPAIAN (Skala 1-4)
# ==========================================================
mean_scores = indikator.mean()
# Menghitung persentase berdasarkan skala maksimal 4
total_avg = mean_scores.mean()
ikm = (total_avg / 4) * 100

def kategori_capaian(x):
    if x >= 80: return "Sangat Baik"
    elif x >= 65: return "Baik"
    elif x >= 50: return "Cukup"
    else: return "Kurang"

col1, col2, col3 = st.columns(3)
col1.metric("📈 Rata-rata Skor", f"{total_avg:.2f}")
col2.metric("🏷️ Kategori", kategori_capaian(ikm))
col3.metric("👥 Total Responden", len(df))

st.divider()

# ==========================================================
# 3️⃣ ANALISIS GAP (Target Skor Sempurna = 4)
# ==========================================================
st.header("🎯 Analisis GAP per Soal")
st.caption("Gap dihitung dari selisih skor maksimal (4) dengan rata-rata saat ini")

gap_scores = 4 - mean_scores
prioritas_soal = gap_scores.idxmax()

fig_gap, ax_gap = plt.subplots(figsize=(12, 5))
gap_scores.plot(kind='bar', color='skyblue', ax=ax_gap)
ax_gap.set_ylabel("Nilai GAP")
ax_gap.set_title("GAP per Indikator Soal")
plt.xticks(rotation=45)
st.pyplot(fig_gap)

st.warning(f"📌 **Prioritas Perbaikan:** Fokus pada **{prioritas_soal}** karena memiliki GAP terbesar ({gap_scores.max():.2f})")

st.divider()

# ==========================================================
# 4️⃣ ANALISIS KORELASI
# ==========================================================
st.header("🔗 Heatmap Korelasi Antar Soal")

corr = indikator.corr()
fig_corr, ax_corr = plt.subplots(figsize=(10, 8))
im = ax_corr.imshow(corr, cmap="RdYlGn", vmin=-1, vmax=1)
plt.colorbar(im)

# Label untuk 20 soal
ax_corr.set_xticks(range(len(corr.columns)))
ax_corr.set_yticks(range(len(corr.columns)))
ax_corr.set_xticklabels(corr.columns, rotation=90)
ax_corr.set_yticklabels(corr.columns)

ax_corr.set_title("Korelasi Pearson (Soal 1 - Soal 20)")
st.pyplot(fig_corr)

st.divider()

# ==========================================================
# 5️⃣ ANALISIS REGRESI (Soal 1-19 terhadap Soal 20)
# ==========================================================
st.header("⚖️ Analisis Regresi Linear")
st.caption("Melihat pengaruh Soal_1 s/d Soal_19 terhadap hasil Soal_20")

X = sm.add_constant(indikator.iloc[:, 0:19])
y = indikator.iloc[:, 19] # Soal_20 sebagai target

model = sm.OLS(y, X, missing="drop").fit()
r2 = model.rsquared

st.info(f"📊 **Nilai R-Squared:** {r2:.3f} (Sejauh mana soal 1-19 menjelaskan variansi soal 20)")

# Menampilkan 5 koefisien tertinggi
coef = model.params[1:].sort_values(ascending=False).head(5)
st.subheader("🔝 5 Faktor Paling Berpengaruh (Koefisien Teratas)")
st.table(coef.to_frame("Koefisien"))

st.divider()

# ==========================================================
# 6️⃣ SEGMENTASI SISWA (K-Means)
# ==========================================================
st.header("👥 Segmentasi Kemampuan Siswa")

scaler = StandardScaler()
X_scaled = scaler.fit_transform(indikator.fillna(0))

kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
cluster_label = kmeans.fit_predict(X_scaled)

indikator_cluster = indikator.copy()
indikator_cluster["Cluster"] = cluster_label

# Mapping kategori berdasarkan rata-rata cluster
cluster_mean = indikator_cluster.groupby("Cluster").mean()
cluster_ranking = cluster_mean.mean(axis=1).sort_values(ascending=False).index

segment_map = {
cluster_ranking[0]: "Kelompok Mahir",
cluster_ranking[1]: "Kelompok Menengah",
cluster_ranking[2]: "Kelompok Dasar"
}

indikator_cluster["Segment"] = indikator_cluster["Cluster"].map(segment_map)

# Tampilkan tabel hasil segmentasi
st.write("Hasil pengelompokan siswa:")
st.dataframe(indikator_cluster[["Segment"]].join(indikator).head(10))

st.success("✅ Dashboard siap digunakan. Silakan sesuaikan kebijakan berdasarkan segmentasi di atas.")
