# -*- coding: utf-8 -*-
"""dashboard-analisis-siswa

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kEOAonUFM3WA6zusWIArZOmkAXxLLgGR
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

# ==========================================================
# KONFIGURASI HALAMAN
# ==========================================================
st.set_page_config(page_title="Dashboard Evaluasi Akademik", layout="wide")
st.title("🎓 Dashboard Evaluasi Akademik Siswa")
st.markdown("Analisis performa siswa berbasis data simulasi")

# ==========================================================
# LOAD DATA
# ==========================================================
file_path = "/content/data_simulasi_50_siswa_20_soal.xlsx"

df = pd.read_excel(file_path)
indikator = df.apply(pd.to_numeric, errors="coerce")

# ==========================================================
# SIDEBAR FILTER
# ==========================================================
st.sidebar.header("⚙️ Pengaturan Dashboard")

pilih_soal = st.sidebar.selectbox(
    "Pilih Soal untuk dianalisis:",
    indikator.columns
)

# ==========================================================
# KPI UTAMA
# ==========================================================
rata_siswa = indikator.mean(axis=1)
rata_keseluruhan = rata_siswa.mean()

col1, col2 = st.columns(2)
col1.metric("📊 Rata-rata Nilai Siswa", f"{rata_keseluruhan:.2f}")
col2.metric("👥 Jumlah Siswa", len(df))

st.divider()

# ==========================================================
# DISTRIBUSI NILAI SISWA
# ==========================================================
st.header("📈 Distribusi Nilai Rata-rata Siswa")

fig1, ax1 = plt.subplots()
ax1.hist(rata_siswa, bins=10)
ax1.set_xlabel("Rata-rata Nilai")
ax1.set_ylabel("Jumlah Siswa")
st.pyplot(fig1)

st.divider()

# ==========================================================
# ANALISIS PER SOAL (INTERAKTIF)
# ==========================================================
st.header(f"📌 Analisis Detail - {pilih_soal}")

fig2, ax2 = plt.subplots()
ax2.boxplot(indikator[pilih_soal])
ax2.set_title(f"Sebaran Nilai {pilih_soal}")
st.pyplot(fig2)

st.write("Rata-rata:", indikator[pilih_soal].mean())
st.write("Standar Deviasi:", indikator[pilih_soal].std())

st.divider()

# ==========================================================
# ANALISIS KORELASI (TOP 5 TERKUAT)
# ==========================================================
st.header("🔗 5 Korelasi Terkuat Antar Soal")

corr = indikator.corr().abs()
corr_unstack = corr.unstack()
corr_unstack = corr_unstack[corr_unstack < 1]
top_corr = corr_unstack.sort_values(ascending=False).drop_duplicates().head(5)

st.table(top_corr)

st.divider()

# ==========================================================
# ANALISIS REGRESI (TARGET BERBEDA)
# ==========================================================
st.header("📉 Analisis Regresi Linear")

target = indikator["Soal_10"]   # beda dari sebelumnya
X = sm.add_constant(indikator.drop(columns=["Soal_10"]))
model = sm.OLS(target, X).fit()

st.info(f"Nilai R-Squared: {model.rsquared:.3f}")

coef = model.params[1:].sort_values(ascending=False).head(5)
st.subheader("Top 5 Variabel Paling Berpengaruh")
st.table(coef)

st.divider()

# ==========================================================
# RANKING SISWA
# ==========================================================
st.header("🏆 Ranking 10 Siswa Terbaik")

df_ranking = indikator.copy()
df_ranking["Total Nilai"] = indikator.sum(axis=1)
ranking = df_ranking.sort_values("Total Nilai", ascending=False).head(10)

st.dataframe(ranking[["Total Nilai"]])

st.divider()

# ==========================================================
# CLUSTERING (4 KELOMPOK)
# ==========================================================
st.header("👥 Segmentasi Siswa (4 Cluster)")

scaler = StandardScaler()
scaled = scaler.fit_transform(indikator.fillna(0))

kmeans = KMeans(n_clusters=4, random_state=42, n_init=10)
cluster = kmeans.fit_predict(scaled)

indikator["Cluster"] = cluster

cluster_summary = indikator.groupby("Cluster").mean().mean(axis=1)
st.write("Rata-rata tiap cluster:")
st.write(cluster_summary)
fig3, ax3 = plt.subplots()
ax3.bar(cluster_summary.index.astype(str), cluster_summary.values)
ax3.set_xlabel("Cluster")
ax3.set_ylabel("Rata-rata Nilai")
st.pyplot(fig3)

st.success("✅ Dashboard versi berbeda berhasil dibuat.")