# -*- coding: utf-8 -*-
"""dashboard_siswa

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12fFOVpqLBX9qQywOwoVH-pfrjlqxg6qJ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

# ==========================================================
# KONFIGURASI HALAMAN (SAMA SEPERTI FILE ASLI)
# ==========================================================
st.set_page_config(page_title="Dashboard Analisis Siswa", layout="wide")
st.title("📊 Dashboard Analisis Hasil Simulasi Siswa")
st.markdown("Aplikasi ini digunakan untuk menganalisis hasil simulasi 50 siswa pada 20 indikator penilaian menggunakan pendekatan statistik dan data mining.")

# ==========================================================
# INPUT DATA
# ==========================================================
uploaded_file = st.file_uploader("Upload file Excel data siswa", type=["/content/data_simulasi_50_siswa_20_soal.xlsx"])

if uploaded_file is None:
    st.info("Silakan upload data terlebih dahulu untuk memulai analisis.")
    st.stop()


# ==========================================================
# INPUT DATA
# ==========================================================
uploaded_file = st.file_uploader("Upload file Excel", type=["xlsx"])

if uploaded_file is None:
    st.warning("Silakan upload file Excel terlebih dahulu.")
    st.stop()
    
# ==========================================================
# MEMBACA DATA
# ==========================================================
try:
    df = pd.read_excel(uploaded_file)
    indikator = df.apply(pd.to_numeric, errors="coerce")
except Exception as e:
    st.error(f"Gagal membaca file: {e}")
    st.stop()

# memastikan numerik
indikator = df.apply(pd.to_numeric, errors="coerce")

st.subheader("📋 Preview Data")
st.write("Menampilkan 5 baris pertama dataset:")
st.dataframe(indikator.head())

st.divider()

# ==========================================================
# STATISTIK DESKRIPTIF
# ==========================================================
st.header("1️⃣ Statistik Deskriptif")

rata_soal = indikator.mean()
std_soal = indikator.std()
rata_total = rata_soal.mean()

indeks_kepuasan = (rata_total / 4) * 100

def kategori(x):
    if x >= 80: return "Sangat Baik"
    elif x >= 65: return "Baik"
    elif x >= 50: return "Cukup"
    else: return "Kurang"

col1, col2, col3, col4 = st.columns(4)
col1.metric("Rata-rata keseluruhan", f"{rata_total:.2f}")
col2.metric("Standar deviasi rata-rata", f"{std_soal.mean():.2f}")
col3.metric("Indeks capaian (%)", f"{indeks_kepuasan:.2f}")
col4.metric("Kategori capaian", kategori(indeks_kepuasan))

st.write("Tabel statistik tiap indikator:")
st.dataframe(pd.DataFrame({
    "Rata-rata": rata_soal,
    "Standar deviasi": std_soal
}))

st.divider()

# ==========================================================
# VISUALISASI DISTRIBUSI NILAI
# ==========================================================
st.header("2️⃣ Distribusi Nilai Siswa")

fig_dist, ax_dist = plt.subplots(figsize=(8,4))
indikator.mean(axis=1).hist(ax=ax_dist, bins=10)
ax_dist.set_title("Distribusi rata-rata nilai siswa")
ax_dist.set_xlabel("Skor rata-rata")
ax_dist.set_ylabel("Frekuensi")
st.pyplot(fig_dist)

st.divider()

# ==========================================================
# ANALISIS GAP
# ==========================================================
st.header("3️⃣ Analisis GAP Kinerja")

gap = 4 - rata_soal
soal_prioritas = gap.idxmax()

fig_gap, ax_gap = plt.subplots(figsize=(10,4))
gap.plot(kind="bar", color="orange", ax=ax_gap)
ax_gap.set_ylabel("GAP terhadap skor maksimum")
ax_gap.set_title("Analisis kesenjangan tiap indikator")
plt.xticks(rotation=45)
st.pyplot(fig_gap)

st.warning(f"Indikator prioritas perbaikan: **{soal_prioritas}**")

st.divider()

# ==========================================================
# KORELASI
# ==========================================================
st.header("4️⃣ Korelasi Antar Indikator")

corr = indikator.corr()
fig_corr, ax_corr = plt.subplots(figsize=(9,7))
im = ax_corr.imshow(corr, cmap="coolwarm", vmin=-1, vmax=1)
plt.colorbar(im, ax=ax_corr)

ax_corr.set_xticks(range(len(corr.columns)))
ax_corr.set_yticks(range(len(corr.columns)))
ax_corr.set_xticklabels(corr.columns, rotation=90)
ax_corr.set_yticklabels(corr.columns)
ax_corr.set_title("Heatmap Korelasi Pearson")

st.pyplot(fig_corr)

st.divider()

# ==========================================================
# REGRESI LINEAR
# ==========================================================
st.header("5️⃣ Analisis Regresi Linear")

X = sm.add_constant(indikator.iloc[:, :-1])
y = indikator.iloc[:, -1]

model = sm.OLS(y, X, missing="drop").fit()

st.write(f"Nilai R² model: **{model.rsquared:.3f}**")

koef = model.params[1:].sort_values(ascending=False)

st.subheader("5 Koefisien terbesar")
st.table(koef.head(5).to_frame("Koefisien"))

st.divider()

# ==========================================================
# SEGMENTASI SISWA
# ==========================================================
st.header("6️⃣ Segmentasi Siswa (Clustering)")

scaler = StandardScaler()
X_scaled = scaler.fit_transform(indikator.fillna(0))

kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
cluster = kmeans.fit_predict(X_scaled)

indikator_cluster = indikator.copy()
indikator_cluster["Cluster"] = cluster

cluster_mean = indikator_cluster.groupby("Cluster").mean()
ranking = cluster_mean.mean(axis=1).sort_values(ascending=False).index

mapping = {
    ranking[0]: "Kelompok Tinggi",
    ranking[1]: "Kelompok Sedang",
        ranking[2]: "Kelompok Rendah"
}

indikator_cluster["Kategori"] = indikator_cluster["Cluster"].map(mapping)

st.write("Contoh hasil segmentasi:")
st.dataframe(indikator_cluster[["Kategori"]].join(indikator).head(10))

st.divider()

# ==========================================================
# INTERPRETASI OTOMATIS
# ==========================================================
st.header("7️⃣ Interpretasi Hasil")

st.write(f"""
Berdasarkan analisis, diperoleh rata-rata capaian siswa sebesar **{rata_total:.2f}**
dengan indeks capaian **{indeks_kepuasan:.2f}%** yang termasuk kategori **{kategori(indeks_kepuasan)}**.

Analisis GAP menunjukkan bahwa indikator **{soal_prioritas}**
merupakan aspek yang paling membutuhkan peningkatan.

Hasil regresi menunjukkan bahwa beberapa indikator memiliki pengaruh signifikan
terhadap capaian akhir siswa, sehingga peningkatan pada indikator tersebut
dapat berdampak langsung terhadap hasil belajar.

Segmentasi siswa menunjukkan adanya kelompok kemampuan berbeda,
yang mengindikasikan perlunya strategi pembelajaran yang lebih adaptif.
""")

st.success("Dashboard selesai dianalisis dan siap digunakan untuk laporan penelitian.")
